//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123TribeFrameworker.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class firstLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public firstLevel()
        {
            this.SecondLevel = new HashSet<SecondLevel>();
        }
    
        public int id { get; set; }
        public string beforContent { get; set; }
        public string midContent { get; set; }
        public string afterContent { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<int> activityFlag { get; set; }
        public int orderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecondLevel> SecondLevel { get; set; }
    }
}
