// <auto-generated />
namespace _123TribeFrameworker.migrations.ApplicationsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitBlogDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitBlogDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201805210321207_InitBlogDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
